version: 0.2

phases:
  pre_build:
    commands:
      - yum update -y
      - sudo amazon-linux-extras install docker
      - service docker start
  build:
    commands:
      - docker build -t flask .